Update terra-docs.yaml

diff --git a/.github/workflows/terra-docs.yaml b/.github/workflows/terra-docs.yaml
--- a/.github/workflows/terra-docs.yaml
+++ b/.github/workflows/terra-docs.yaml
@@ -23,30 +23,59 @@ jobs:
 
       - name: Install Dependencies
         run: |
+          RED='\033[0;31m'
+          GREEN='\033[0;32m'
+          
           # Update package lists
           sudo apt-get update
 
-          # Install Terraform
-          sudo apt-get install -y wget unzip
-          wget https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
-          unzip terraform_1.5.4_linux_amd64.zip
-          sudo mv terraform /usr/local/bin/
-          terraform --version
+          # Check and Install Terraform
+          if ! command -v terraform &> /dev/null; then
+            echo "${RED}Terraform not found, installing..."
+            sudo apt-get install -y wget unzip
+            wget https://releases.hashicorp.com/terraform/1.11.1/terraform_1.11.1_linux_amd64.zip
+            unzip terraform_1.5.4_linux_amd64.zip
+            sudo mv terraform /usr/local/bin/
+          else
+            echo "${GREEN}Terraform is already installed. Current version:"
+            terraform --version
+          fi
 
-          # Install Graphviz
-          sudo apt-get install -y graphviz
-          dot -V # Verify Graphviz installation
+          # Check and Install Graphviz
+          if ! command -v dot &> /dev/null; then
+            echo "${RED}Graphviz not found, installing..."
+            sudo apt-get install -y graphviz
+          else
+            echo "${GREEN}Graphviz is already installed. Current version:"
+            dot -V
+          fi
 
-          # Install Terraform Docs
-          curl -s https://raw.githubusercontent.com/terraform-docs/terraform-docs/main/install.sh | bash
-          terraform-docs --version # Verify Terraform Docs installation
+          # Check and Install Terraform Docs
+          if ! command -v terraform-docs &> /dev/null; then
+            echo "${RED}Terraform Docs not found, installing..."
+            curl -s https://raw.githubusercontent.com/terraform-docs/terraform-docs/main/install.sh | bash
+          else
+            echo "${GREEN}Terraform Docs is already installed. Current version:"
+            terraform-docs --version
+          fi
 
-          # Install Python3 and Pip (for Rover)
-          sudo apt-get install -y python3 python3-pip
+          # Check and Install Python3 and Pip (for Rover)
+          if ! command -v python3 &> /dev/null; then
+            echo "${RED}Python3 not found, installing..."
+            sudo apt-get install -y python3 python3-pip
+          else
+            echo "${GREEN}Python3 is already installed. Current version:"
+            python3 --version
+          fi
 
-          # Install Rover
-          pip3 install rover
-          rover --version # Verify Rover installation
+          # Check and Install Rover
+          if ! pip3 show rover > /dev/null 2>&1; then
+            echo "${RED}Rover not found, installing..."
+            pip3 install rover
+          else
+            echo "R${GREEN}over is already installed. Current version:"
+            rover --version
+          fi
       # Step 1: Checkout Code
       - name: Checkout code
         uses: actions/checkout@v4
